title = "Gitleaks configuration for MCP CICD"

[[rules]]
description = "Generic API Key"
regex = '''(?i)api[_-]?key["']?\s*[:=]\s*["'][a-z0-9_\-]{20,}["']'''
tags = ["key", "api-key"]

[[rules]]
description = "Generic Secret"
regex = '''(?i)secret["']?\s*[:=]\s*["'][a-z0-9_\-]{20,}["']'''
tags = ["secret", "generic"]

[[rules]]
description = "AWS Access Key ID"
regex = '''(?i)aws[_-]?access[_-]?key[_-]?id["']?\s*[:=]\s*["'][A-Z0-9]{16,}["']'''
tags = ["aws", "key"]

[[rules]]
description = "AWS Secret Access Key"
regex = '''(?i)aws[_-]?secret[_-]?access[_-]?key["']?\s*[:=]\s*["'][a-zA-Z0-9/+]{40}["']'''
tags = ["aws", "secret"]

[[rules]]
description = "GitHub Token"
regex = '''(?i)github[_-]?token["']?\s*[:=]\s*["'][a-z0-9_\-]{40}["']'''
tags = ["github", "token"]

[[rules]]
description = "SSH Private Key"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'''
tags = ["ssh", "private-key"]

[[rules]]
description = "JWT"
regex = '''eyJ[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*\.[a-zA-Z0-9_-]*'''
tags = ["jwt", "token"]

[[rules]]
description = "Password in URL"
regex = '''[a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}'''
tags = ["password", "url"]